Add stop command and alias to README
vivid-planet/comet pull request #1051
Opened 2023-04-12 09:22 UTC by max-debug022

The README file was extended to further improve the usability.

2023-04-12 09:26 UTC, dkarnutsch commented on README.md
> +
the alias is already documented here: https://github.com/vivid-planet/dev-process-manager, so I would remove this

2023-04-12 09:26 UTC, dkarnutsch commented on README.md
> +```
It is not clear that dev-pm is used, so I would state its usage somewhere above, so this makes sense

2023-04-13 09:25 UTC, johnnyomair requested changes

2023-04-13 09:25 UTC, johnnyomair commented on README.md
> +The Node.js process manager "dev-process-manager" (https://github.com/vivid-planet/dev-process-manager) is used in the local development environment.
```suggestion
[dev-process-manager](https://github.com/vivid-planet/dev-process-manager) is used for local development.
```

I'd move this clarification into the "Start development processes" section

2023-04-14 07:54 UTC, dkarnutsch approved these changes

2023-04-17 08:21 UTC, johnnyomair approved these changes

2023-04-17 08:21 UTC, merged