Add CrudVisibility component for implementing visibility column in a Crud Grid
vivid-planet/comet pull request #1116
Opened 2023-05-16 16:33 UTC by nsams

This should be best practice and will be used by admin generator

2023-05-22 11:51 UTC, dkarnutsch commented on packages/api/cms-api/src/generator/generate-crud-input.ts
> +        if (prop.name === "id" || prop.name == "createdAt" || prop.name == "updatedAt" || prop.name == "visible") {
OPT

```suggestion
        if (["id", "createdAt", "updatedAt", "visible"].includes(prop.name)) {
```

2023-05-25 10:57 UTC, johnnyomair commented on packages/admin/admin/src/dataGrid/CrudVisibility.tsx
> +                        }}
Shouldn't using the boolean work directly?

```tsx
<FormattedMessage
  id="comet.common.visibilityChanged"
  defaultMessage="Changed visibility to {visibility, select, true {published} false {unpublished} other {unknown}}"
  values={{ visibility }}
/>
```

2023-06-07 10:43 UTC, johnnyomair requested changes

2023-06-07 10:43 UTC, johnnyomair commented on packages/admin/admin/src/dataGrid/CrudVisibilityIcon.tsx
> +export function CrudVisibilityIcon({ visibility, disabled }: CrudVisibilityIconProps): JSX.Element {
```suggestion
export function CrudVisibilityIcon({ visibility }: CrudVisibilityIconProps): JSX.Element {
```

2023-06-07 10:43 UTC, johnnyomair commented on packages/admin/admin/src/dataGrid/CrudVisibilityIcon.tsx
> +    disabled?: boolean;
```suggestion
```

2023-06-13 06:47 UTC, johnnyomair submitted a review, later dismissed

2023-06-13 06:52 UTC, johnnyomair approved these changes

2023-06-13 10:41 UTC, johnnyomair approved these changes

2023-06-13 10:41 UTC, merged