Type GraphQL DateTime scalar in GraphQL Code Generator
vivid-planet/comet pull request #1245
Opened 2023-08-31 14:11 UTC by Ben-Ho

needed to improve starter: https://github.com/vivid-planet/comet-starter/pull/10

2023-08-31 16:03 UTC, Ben-Ho commented
@nsams @johnnyomair lint failes but I don't understand why.

who does generate the types used here: https://github.com/vivid-planet/comet/blob/main/demo/admin/src/links/EditLink.tsx#L8, especially GQLUpdateLinkMutation. I would expect them to be based on this gql-query: https://github.com/vivid-planet/comet/blob/main/demo/admin/src/links/EditLink.tsx#L40 or does this generate from somewhere else? (same for savePage)

probably it's because of https://github.com/vivid-planet/comet/blob/main/demo/admin/codegen.ts#L31

lastUpdatedAt in api-schema should be optional, as it's defined as nullable here: https://github.com/vivid-planet/comet/blob/main/demo/api/src/links/links.resolver.ts#L26. Also schema does not contain a !.

2023-09-04 05:59 UTC, nsams commented
you are mixing input and response (in response it is non-nullable, in input it is nullable)

the proper fix is `lastUpdatedAt?: string | null;` I guess.

Can you reproduce the problem the pipeline reports locally?

2023-09-11 13:37 UTC, johnnyomair requested changes
You can't remove the optional identifier `?` for `lastUpdatedAt`, as variables in GraphQL mutations can be both absent (= undefined) and set to null. Adding the suggestions I proposed should resolve the pipeline issues

2023-09-11 13:37 UTC, johnnyomair commented on packages/admin/cms-admin/src/pages/createUsePage.tsx
> +            lastUpdatedAt: string | null;
```suggestion
            lastUpdatedAt?: string | null;
```

2023-09-11 13:37 UTC, johnnyomair commented on packages/admin/cms-admin/src/pages/createUsePage.tsx
> +            lastUpdatedAt: string | null;
```suggestion
            lastUpdatedAt?: string | null;
```

2023-09-11 13:38 UTC, johnnyomair commented
I think we should also change the codegen config for the Demo site

2023-09-14 08:08 UTC, johnnyomair approved these changes

2023-09-14 08:52 UTC, nsams approved these changes

2023-09-14 08:52 UTC, nsams commented
please continue in starter

2023-09-14 08:53 UTC, merged

2023-09-14 08:53 UTC, johnnyomair commented
> please continue in starter

We'll need a stable release for it

2023-09-14 13:09 UTC, thomasdax98 commented
@johnnyomair @nsams Does this qualify as a patch? Then we could make a 4.4.2 Release. The only thing missing is a changeset for this change

2023-09-14 13:19 UTC, nsams commented
Why not, or is there more coming we could wait for?

2023-09-15 07:38 UTC, thomasdax98 commented
@nsams We could wait for https://github.com/vivid-planet/comet/pull/1266 and https://github.com/vivid-planet/comet/pull/1267