Allow forcing a Block Index Update via GraphQL Query
vivid-planet/comet pull request #1259
Opened 2023-09-11 15:03 UTC by thomasdax98

depends on https://github.com/vivid-planet/comet/pull/1222

- add a `force` arg to `dependencies()` and `dependents()` field resolver

2023-09-11 15:11 UTC, nsams commented on packages/api/cms-api/src/dependencies/dto/dependencies.args.ts
> +    @Field(() => Boolean, { nullable: true, defaultValue: false })
doesn't have to be nullable if you specify a defaultValue

2023-09-11 15:12 UTC, nsams commented on packages/api/cms-api/src/dependencies/dto/dependencies.args.ts
> +    force: boolean;
force in the graphql api is a bit strange parameter name, alternatives:

- forceRefresh
- refresh
- update
- forceUpdate

2023-09-12 07:11 UTC, johnnyomair reviewed
Is it a good idea to do this as a side effect of the dependents/dependencies queries? Shouldn't this be a separate mutation, for instance, refreshDependencies?

2023-09-12 09:13 UTC, nsams commented
> Is it a good idea to do this as a side effect of the dependents/dependencies queries? Shouldn't this be a separate mutation, for instance, refreshDependencies?

I think it is Ok. With a mutation you win nothing only complicate things.

2023-09-12 16:05 UTC, nsams commented on packages/api/cms-api/src/dependencies/dto/dependencies.args.ts
> +    @IsUndefinable()
```suggestion
```

2023-09-13 07:22 UTC, johnnyomair requested changes

2023-09-13 07:22 UTC, johnnyomair commented on packages/api/cms-api/src/dependencies/dto/dependencies.args.ts
> +    @IsUndefinable()
```suggestion
```

2023-09-13 17:55 UTC, nsams approved these changes

2023-09-14 06:44 UTC, johnnyomair approved these changes

2023-09-14 06:44 UTC, merged