COM-139: Add Comet UX Library Icons
vivid-planet/comet pull request #1462
Opened 2023-11-30 10:53 UTC by jomunker

This PR adds new icons from the Comet UX library. It also replaces existing icons with new versions and deprecates the icons `pool`, `pool2`, `vignette1`, `vignette2`, `Betrieb` and `LogischeFilter`.

## Acceptance Criteria
- [x] Add changeset

2023-11-30 11:45 UTC, thomasdax98 commented on packages/admin/admin-icons/src/Betrieb.tsx
> + * @deprecated The 'Betrieb' icon will be removed in the next release.
```suggestion
 * @deprecated The 'Betrieb' icon will be removed in v6.
```

2023-11-30 11:45 UTC, thomasdax98 commented on packages/admin/admin-icons/src/LogischeFilter.tsx
> + * @deprecated The 'LogischeFilter' icon will be removed in the next release.
```suggestion
 * @deprecated The 'LogischeFilter' icon will be removed in v6.
```

2023-11-30 11:45 UTC, thomasdax98 commented on packages/admin/admin-icons/src/Pool2.tsx
> + * @deprecated The 'Pool2' icon will be removed in the next release.
```suggestion
 * @deprecated The 'Pool2' icon will be removed in v6.
```

2023-11-30 11:45 UTC, thomasdax98 commented on packages/admin/admin-icons/src/Vignette2.tsx
> + * @deprecated The 'Vignette2' icon will be removed in the next release.
```suggestion
 * @deprecated The 'Vignette2' icon will be removed in v6.
```

2023-12-06 07:35 UTC, jomunker commented on .changeset/real-cars-impress.md
> +"@comet/admin-icons": minor
Don't know actually 🤔 I'll ask Mitch

2023-12-06 14:55 UTC, thomasdax98 submitted a review, later dismissed

2023-12-11 13:00 UTC, johnnyomair requested changes
Some icons (e.g. Frame80) need to be updated before merging

2023-12-12 10:16 UTC, johnnyomair approved these changes

2023-12-12 10:17 UTC, merged