COM-323 Refactor theming of `RouterTabs`
vivid-planet/comet pull request #1558
Opened 2024-01-10 12:51 UTC by NataliaVizintini

<img width="669" alt="Screenshot 2024-01-10 at 13 48 41" src="https://github.com/vivid-planet/comet/assets/72875628/02a3eab7-5f90-4c86-804c-1d0247ab237e">

2024-01-10 14:00 UTC, jamesricky requested changes

2024-01-10 14:00 UTC, jamesricky commented on packages/admin/admin/src/tabs/RouterTabs.tsx
> +        <Root {...slotProps?.root}>
The `sx` and `className` props should be passed into the `Root`, you can probably do it with `...restProps`.

2024-01-10 15:27 UTC, jamesricky submitted a review, later dismissed

2024-01-22 15:43 UTC, johnnyomair submitted a review, later dismissed

2024-01-22 15:43 UTC, johnnyomair commented
@NataliaVizintini please resolve conflicts

2024-01-22 15:52 UTC, johnnyomair approved these changes

2024-01-22 15:58 UTC, merged