COM-321 Refactor theming of FilterBarMoreFilters
vivid-planet/comet pull request #1588
Opened 2024-01-17 12:57 UTC by juliawegmayr

<img width="474" alt="Screenshot 2024-01-17 at 13 56 26" src="https://github.com/vivid-planet/comet/assets/109900447/a16adc13-ff2a-45bf-9755-f65da4639a8a">
<img width="163" alt="Screenshot 2024-01-17 at 13 56 31" src="https://github.com/vivid-planet/comet/assets/109900447/29f92594-2723-450c-a062-1f900642c8be">

2024-01-23 07:59 UTC, jamesricky requested changes

2024-01-23 07:59 UTC, jamesricky commented on .changeset/happy-ladybugs-smile.md
> +Rename `FilterBarMoveFilersClassKey` in `FilterBarMoreFiltersClassKey`
Good catch 😄

2024-01-23 07:59 UTC, jamesricky commented on .changeset/happy-ladybugs-smile.md
> +Rename `FilterBarMoveFilersClassKey` in `FilterBarMoreFiltersClassKey`
```suggestion
Rename `FilterBarMoveFilersClassKey` to `FilterBarMoreFiltersClassKey`
```

2024-01-23 07:59 UTC, jamesricky commented on packages/admin/admin/src/table/filterbar/filterBarMoreFilters/FilterBarMoreFilters.tsx
>   */
The deprecation notice needs to stay directly above the Props type.

2024-01-23 07:59 UTC, jamesricky commented on packages/admin/admin/src/table/filterbar/filterBarMoreFilters/FilterBarMoreFilters.tsx
> - */
The deprecation notice needs to stay directly above the exported component.

2024-01-23 07:59 UTC, jamesricky commented on packages/admin/admin/src/table/filterbar/filterBarMoreFilters/FilterBarMoreFilters.tsx
> +export function FilterBarMoreFilters(children: React.PropsWithChildren<FilterBarMoreFiltersProps>, inProps: FilterBarMoreFiltersProps) {
I don't think this works, the first parameter is always the props and the children are inside the props. 

```suggestion
export function FilterBarMoreFilters(inProps: React.PropsWithChildren<FilterBarMoreFiltersProps) {
```

2024-01-23 07:59 UTC, jamesricky commented on packages/admin/admin/src/table/filterbar/filterBarMoreFilters/FilterBarMoreFilters.tsx
> +export interface FilterBarMoreFiltersProps extends ThemedComponentBaseProps<{ root: any; button: typeof FilterBarButton }> {
Please set the actual type

```suggestion
export interface FilterBarMoreFiltersProps extends ThemedComponentBaseProps<{
    root: "div";
    button: typeof FilterBarButton;
}> {
```

2024-01-24 10:38 UTC, jamesricky requested changes

2024-01-24 10:38 UTC, jamesricky commented on packages/admin/admin/src/table/filterbar/filterBarMoreFilters/FilterBarMoreFilters.tsx
> +export type FilterBarMoreFiltersClassKey = "root" | "button";
please re-add the deprecation notice

2024-01-26 10:26 UTC, jamesricky approved these changes

2024-01-29 15:57 UTC, johnnyomair approved these changes

2024-01-29 15:58 UTC, merged