Refactor theming of 'Toolbar' in admin-rte
vivid-planet/comet pull request #1601
Opened 2024-01-22 08:52 UTC by andrearutrecht

Refactored theming of 'Toolbar' in admin-rte.
Toolbar has been tested locally.

![Screenshot 2024-01-22 at 09 49 18](https://github.com/vivid-planet/comet/assets/122883866/712173c1-dde8-4dc5-b083-c1153484c959)

2024-01-24 12:52 UTC, jamesricky submitted a review, later dismissed

2024-01-25 13:47 UTC, johnnyomair submitted a review, later dismissed

2024-01-25 13:47 UTC, johnnyomair commented
@andrearutrecht the pipeline fails. Please run `pnpm install` in the root and commit the changes in the lock file

2024-01-26 09:39 UTC, jamesricky approved these changes

2024-01-29 16:22 UTC, johnnyomair submitted a review, later dismissed

2024-01-29 16:23 UTC, johnnyomair commented
@andrearutrecht please resolve conflicts (sorry)

2024-01-30 13:39 UTC, andrearutrecht commented
@johnnyomair merge conflicts are now solved

2024-01-30 13:40 UTC, johnnyomair requested changes

2024-01-30 14:33 UTC, merged