COM-308 Refactor theming of `MasterLayout`
vivid-planet/comet pull request #1603
Opened 2024-01-22 10:09 UTC by NataliaVizintini

<img width="1283" alt="Screenshot 2024-01-22 at 11 09 05" src="https://github.com/vivid-planet/comet/assets/72875628/ef3ec2a0-1c4d-46dd-9edd-f42f3c274fdb">

2024-01-23 09:31 UTC, jamesricky requested changes

2024-01-23 09:31 UTC, jamesricky commented on packages/admin/admin/src/mui/MasterLayout.tsx
> +        z-index: "zIndex.drawer - 10";
A string will not work here, you need to subtract 10 form the theme-value.

2024-01-23 09:31 UTC, jamesricky commented on packages/admin/admin/src/mui/MasterLayout.tsx
> +        flex-grow: "1";
This needs to be the css-syntax, not the object-syntax, as in the previous styling-method. 

```suggestion
        flex-grow: 1;
```

2024-01-24 13:19 UTC, jamesricky commented on packages/admin/admin/src/mui/MasterLayout.tsx
> +        z-index: ${theme.zIndex.drawer} - 10;
Does this work? I think this would be the correct syntax:

```suggestion
        z-index: ${theme.zIndex.drawer - 10};
```

2024-01-25 08:33 UTC, jamesricky approved these changes

2024-01-25 13:44 UTC, johnnyomair approved these changes

2024-01-25 13:44 UTC, merged