COM-314: Refactor theming of `StackBreadcrumbs`
vivid-planet/comet pull request #1606
Opened 2024-01-22 13:21 UTC by juliawegmayr

<img width="336" alt="Screenshot 2024-01-22 at 14 19 12" src="https://github.com/vivid-planet/comet/assets/109900447/d1322d17-723b-469d-9021-23cd23a4e7b3">

2024-01-23 10:27 UTC, jamesricky requested changes

2024-01-23 10:27 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +                <StyledDisabledLink {...slotProps?.styledDisabledLink} variant="body2">
The disabled item should not be changed to a link

2024-01-23 10:27 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +export type BreadcrumbsEntryClassKey = "backButtonSeparator" | "link" | "disabledLink";
I don't think there's a good reason to remove/rename all those class keys... seems linke an unnecessary breaking change to me that now removes the ability to style certain elements entirely.

2024-01-23 10:27 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +    extends ThemedComponentBaseProps<{ styledLink: typeof Link; backButtonSeparator: "div"; styledDisabledLink: typeof Link }> {
The keys here need to match the values in the `ClassKey` type

2024-01-24 14:21 UTC, jamesricky requested changes

2024-01-24 14:21 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +                    <IconButton component={BreadcrumbLink} to={backButtonUrl}>
This should be a slot that extends `IconButton`

2024-01-24 14:21 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +        color: ${theme.palette.grey[600]};
```suggestion
```

2024-01-24 14:21 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +        return [styles.disabledLink];
This should also include the styles of the non-disabled link, as in the previous implementation. 

```suggestion
        return [styles.link, styles.disabledLink];
```

2024-01-24 14:21 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +    const { item, isLastItem, backButtonUrl, slotProps } = useThemeProps({ props: inProps, name: "CometAdminBreadcrumbsEntry" });
`ThemedComponentBaseProps`, its slot-types and `useThemeProps` should only be defined/used in the "primary" component `StackBreadcrumbs` as `BreadcrumbsEntry` is not an exported component but only used internally by `StackBreadcrumbs`.

2024-01-31 07:37 UTC, jamesricky requested changes
Please use the correct type for `slotProps` instead of `any`. 

`StackBreadcrumbsProps["slotProps"]`

2024-01-31 07:37 UTC, jamesricky commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsOverflow.tsx
> +export interface BreadcrumbsOverflowProps {
There is no need to export this interface. 

```suggestion
interface BreadcrumbsOverflowProps {
```

2024-02-07 10:49 UTC, jamesricky submitted a review, later dismissed

2024-02-13 14:23 UTC, johnnyomair requested changes

2024-02-13 14:23 UTC, johnnyomair commented on packages/admin/admin/src/stack/breadcrumbs/BreadcrumbsEntry.tsx
> +const StyledLink = styled(Link, {
I'd prefer if you'd remove the Styled prefixes... They don't really add any meaning to the components. For the name clash on Link you could import the Link as `Link as MuiLink`

2024-02-20 06:17 UTC, jamesricky approved these changes

2024-02-21 09:20 UTC, johnnyomair approved these changes

2024-02-21 09:20 UTC, merged