Refactor theming of `Rte` in `/admin-rte`
vivid-planet/comet pull request #1660
Opened 2024-02-06 07:48 UTC by andrearutrecht

Styling of  `Rte` in `/admin-rte` is refactored.

<details><summary>Video of Rte:</summary>
<p>

https://github.com/vivid-planet/comet/assets/122883866/6496ca9e-8697-4caf-afae-53d9c7fc4a8c

</p>
</details> 

<details><summary>Video of disabled Rte:</summary>
<p>

https://github.com/vivid-planet/comet/assets/122883866/28563d3f-5ae4-4e5a-82a2-f5b0ace65ea8

</p>
</details> 

- [ ] Add changeset (if necessary)

2024-02-07 10:38 UTC, jamesricky requested changes

2024-02-07 10:38 UTC, jamesricky commented on packages/admin/admin-rte/src/core/Rte.tsx
> +        `}
Shouldn't this be part of `.public-DraftEditor-content`?

2024-02-07 10:38 UTC, jamesricky commented on packages/admin/admin-rte/src/core/Rte.tsx
> +            disabled,
This is missing `minHeight`

2024-02-07 10:38 UTC, jamesricky commented on packages/admin/admin-rte/src/core/Rte.tsx
> +            min-height: 240px;
This is different, than the previous implementation: `${props.minHeight === undefined ? 240 : props.minHeight}px`

2024-02-07 10:38 UTC, jamesricky commented on packages/admin/admin-rte/src/core/Rte.tsx
> +export default Rte;
The default export is no longer required, if `Rte` is already exported

2024-02-08 07:20 UTC, jamesricky submitted a review, later dismissed

2024-02-08 07:21 UTC, jamesricky commented
@andrearutrecht please resolve the conflicts

2024-02-08 09:24 UTC, jamesricky submitted a review, later dismissed

2024-02-13 14:27 UTC, johnnyomair requested changes

2024-02-13 14:27 UTC, johnnyomair commented on packages/admin/admin-rte/src/core/Rte.tsx
> +        let options = rteOptions ? { ...defaultOptions, ...rteOptions } : defaultOptions;
Please keep the name `passedOptions`. Both default options as well as passed options are valid RTE options.

2024-02-15 07:14 UTC, jamesricky requested changes

2024-02-15 07:14 UTC, jamesricky commented on packages/admin/admin-rte/src/core/Rte.tsx
> +            defaultProps?: Partial<ComponentsPropsList["CometAdminRte"]>;
This is already defined as `Partial` in `ComponentsPropsList`

```suggestion
            defaultProps?: ComponentsPropsList["CometAdminRte"];
```

2024-02-15 07:41 UTC, jamesricky approved these changes

2024-02-19 09:49 UTC, johnnyomair approved these changes

2024-02-19 09:49 UTC, merged