COM-294: Refactor theming of `AppHeaderMenuButton`
vivid-planet/comet pull request #1680
Opened 2024-02-09 11:44 UTC by stekalt

<details><summary>AppHeaderMenuButton</summary>
https://github.com/vivid-planet/comet/assets/71731085/97972bb0-19d1-4a9a-989c-9d97574004d0
</details> 

<details><summary>AppHeaderMenuButton themed</summary>
https://github.com/vivid-planet/comet/assets/71731085/181f4d37-2769-4e3a-892b-09265b33a8a4
</details>

2024-02-09 13:01 UTC, jamesricky requested changes

2024-02-09 13:01 UTC, jamesricky commented on packages/admin/admin/src/appHeader/menuButton/AppHeaderMenuButton.tsx
> +        <Root onClick={toggleOpen} {...restProps} size="large">
`restProps` should probably be moved to the end, so they can override `size`

```suggestion
        <Root onClick={toggleOpen} size="large" {...restProps}>
```

2024-02-12 14:43 UTC, jamesricky approved these changes

2024-02-13 09:55 UTC, johnnyomair approved these changes

2024-02-13 09:55 UTC, merged