COM-296: Refactor theming of `HoverActions`
vivid-planet/comet pull request #1687
Opened 2024-02-12 09:13 UTC by stekalt

<details>
    <summary>HoverActions in Table</summary>

https://github.com/vivid-planet/comet/assets/71731085/74f18dfa-9f3c-45ae-9467-1a21730257d2

</details>

2024-02-12 09:50 UTC, jamesricky requested changes

2024-02-12 09:50 UTC, jamesricky commented on packages/admin/admin/src/common/HoverActions.tsx
> +                </Actions>
`restProps` should only be passed through to the Root slot. 

```suggestion
                <Actions {...slotProps?.actions}>
                    {actions}
                </Actions>
```

2024-02-12 09:50 UTC, jamesricky commented on packages/admin/admin/src/common/HoverActions.tsx
> +            </Children>
`restProps` should only be passed through to the Root slot. 

```suggestion
            <Children {...slotProps?.children}>
                {children}
            </Children>
```

2024-02-13 08:00 UTC, jamesricky approved these changes

2024-02-13 09:54 UTC, johnnyomair approved these changes

2024-02-13 09:55 UTC, merged