COM-447: fix Product Form Fields showing double Asterisk
vivid-planet/comet pull request #1917
Opened 2024-04-04 13:15 UTC by jomunker

---

## Description
Fix product form fields showing double asterisk by removing the `requiredSymbol` prop, which was used to render a custom symbol for required fields. We now use the native implementation of the required attribute of MUI to ensure better accessibility and compatibility with screen readers. 

## PR Checklist
-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [ ] Link to the respective task if one exists: 
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary><h2>Screenshots/screencasts</h2></summary>

### Before
![image](https://github.com/vivid-planet/comet/assets/56400587/492ef852-4d2a-47ac-9bd4-a68c11821d78)
### After
<img width="645" alt="image" src="https://github.com/vivid-planet/comet/assets/56400587/3d8d292b-068b-4c69-8214-d2886791e4c2">
</details>

2024-04-08 13:04 UTC, jamesricky requested changes

2024-04-08 13:05 UTC, jamesricky commented
@jomunker please rebase on `next`, that should fix the pipeline.

2024-04-09 06:53 UTC, jamesricky commented on .changeset/gentle-chefs-sell.md
> +Remove `requiredSymbol` Prop from `FieldContainer` component and use native implementation
```suggestion
Remove the `requiredSymbol` prop from `FieldContainer` and use MUIs native implementation
```

2024-04-09 12:40 UTC, jamesricky approved these changes

2024-04-15 09:25 UTC, johnnyomair approved these changes

2024-04-15 09:26 UTC, merged