Refactor Kubernetes localMode
vivid-planet/comet pull request #2094
Opened 2024-05-22 10:43 UTC by dkarnutsch

- Use Guard to avoid code duplication
- Use prevention everywhere for consistent behavior
- Better error message

---

## PR Checklist

-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)

2024-05-23 12:26 UTC, johnnyomair requested changes

2024-05-23 12:26 UTC, johnnyomair commented on packages/api/cms-api/src/kubernetes/prevent-local-invocation.guard.ts
> +            this.logger.warn("Local invocaion not allowed, because the handler is related to build and/or Kubernetes");
```suggestion
            this.logger.warn("Local invocation not allowed, because the handler is related to build and/or Kubernetes");
```

2024-05-27 11:29 UTC, dkarnutsch commented on packages/api/cms-api/src/kubernetes/prevent-local-invocation.guard.ts
> +            this.logger.warn("Local invocaion not allowed, because the handler is related to build and/or Kubernetes");
94dc6b0769e9dc464a45178f3c14c17eef2963b8

2024-05-27 12:59 UTC, johnnyomair approved these changes

2024-05-27 13:00 UTC, merged