Admin Generator (Future): Implement option to set `initialSort` for grids
vivid-planet/comet pull request #2365
Opened 2024-07-31 09:04 UTC by andrearutrecht

A new option is added to `GridConfig`. `initialSort` can now be set for generated Grids.

---

## PR Checklist

-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [x] Link to the respective task if one exists: SVK-273
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
The initalSort in this example is:  column "In stock" DESC, column "Price" ASC

<img width="1558" alt="Screenshot 2024-07-31 at 10 54 27" src="https://github.com/user-attachments/assets/a691272a-60d1-4249-bcef-a03ed559b162">

</details>

2024-08-01 06:22 UTC, johnnyomair commented on .changeset/tame-candles-switch.md
> +Setting the `initialSortProp` option allows to pass an initial sort to the generated Grid.
```suggestion
Setting the `initialSortProp` option allows to pass an initial sort to the generated grid.
```

2024-08-01 06:22 UTC, johnnyomair commented on packages/admin/cms-admin/src/generator/future/generateGrid.ts
> +              config.initialSortProp ? `{ initialSort: initialSort }` : ""
```suggestion
              config.initialSortProp ? `{ initialSort }` : ""
```

2024-08-06 09:03 UTC, johnnyomair requested changes

2024-08-06 09:03 UTC, johnnyomair commented on .changeset/tame-candles-switch.md
We decided to not add changesets for the future Admin Generator for now, so please remove it.

2024-08-06 12:39 UTC, nsams commented
did you consider the alternative to define the initialSort in the config itself? (And not pass it as prop)

That way you can specify a custom initialSort, but not a dynamic one. That would be so much easier to use - or are there use cases where it needs to be dynamic?

2024-08-07 06:32 UTC, andrearutrecht commented
> did you consider the alternative to define the initialSort in the config itself? (And not pass it as prop)

Yes, I did. Actually, this was my initial interpretation of this task. @Ben-Ho then informed me, that this task is specifically about passing the filter as a prop.

2024-08-08 10:57 UTC, nsams commented
> Yes, I did. Actually, this was my initial interpretation of this task. @Ben-Ho then informed me, that this task is specifically about passing the filter as a prop.

Ok, then please add more Context to this PR. Why do we need this? What would be the alternatives?

And: I would like the initialSort-in-config version in any way, to me this seems like the more common use case

2024-08-13 11:43 UTC, andrearutrecht commented
> And: I would like the initialSort-in-config version in any way, to me this seems like the more common use case

@johnnyomair  Should I add that as well?

2024-08-13 11:44 UTC, johnnyomair commented
> > And: I would like the initialSort-in-config version in any way, to me this seems like the more common use case
> 
> @johnnyomair Should I add that as well?

Yes, but please as a separate PR.

2024-08-13 12:17 UTC, johnnyomair commented
@andrearutrecht I just discussed this with @Ben-Ho and we noticed that there isn't a use case at the current time which would require setting the sort via a prop. So please only implement setting the initial sort via config and close this PR, thanks! Sorry for the additional effort 😬

2024-08-13 12:27 UTC, closed without merging