Fix Async SelectField in Storybook
vivid-planet/comet pull request #2461
Opened 2024-08-23 11:52 UTC by fichtnerma

---
Fix Bug where changing option in async Select was not displayed correctly in Storybook Story

## PR Checklist

-   [ ] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [ ] Link to the respective task if one exists: COM-970
-   [ ] Provide screenshots/screencasts if the change contains visual changes

2024-09-10 07:49 UTC, johnnyomair requested changes
Please provide more information in the PR's description. It should be possible to understand what you're doing without having to look at the JIRA task. Also, describe what and how you're fixing. This could then be the commit message of the squashed commit, making the change more comprehensible.

2024-09-10 07:49 UTC, johnnyomair commented on storybook/src/docs/hooks/useAsyncOptionsProps/useAsyncOptionsPropsSelect.stories.tsx
> +
Come on 😁

2024-09-10 09:09 UTC, johnnyomair commented on storybook/src/docs/hooks/useAsyncOptionsProps/useAsyncOptionsPropsSelect.stories.tsx
> +            <Form onSubmit={() => {}} keepDirtyOnReinitialize initialValues={{ selectAsync: { value: "strawberry", label: "Strawberry" } }}>
Please try to fix this differently, either bei memo'ing the initialValues, or declaring the options objects in a variable and using the same object for the initial value. See https://github.com/vivid-planet/comet/blob/main/storybook/src/docs/form/components/stories/FinalFormFields.stories.tsx#L69-L84

2024-09-10 10:29 UTC, fichtnerma commented on storybook/src/docs/hooks/useAsyncOptionsProps/useAsyncOptionsPropsSelect.stories.tsx
> +
Sorry must have missed that

2024-09-16 12:51 UTC, johnnyomair approved these changes

2024-09-16 12:52 UTC, merged