COM-1083: UI for impersonation
vivid-planet/comet pull request #2583
Opened 2024-10-01 07:04 UTC by jomunker

## Description
This PR adds new UI for the impersonation feature implemented in #2490.
It features an indicator for impersonation in the `UserHeaderItem` to showcase, when the impersonation mode is active.
Additionally two placed to activate the mode were added. In the `UserPermissions` List and in the detail view of a User in a `MoreActions` Dropdown.

## Example

-   [ ] I have verified if my change requires an example

## Screenshots/screencasts

### UserHeaderItem
#### Normal State
<img width="421" alt="image" src="https://github.com/user-attachments/assets/e0bdb78e-842f-4644-8f28-fb909b9b9d12">

#### Impersonation mode
<img width="380" alt="image" src="https://github.com/user-attachments/assets/f1147680-e54c-4fab-9b32-f1d333b50cef">

### User Permissions List - Impersonation Button

https://github.com/user-attachments/assets/a3f3be77-d3d2-4417-a225-67bbcb796e3b

### User Permissions Detail View - More Actions

https://github.com/user-attachments/assets/fd4e6de6-9bfd-4df7-a309-a7c82037863a

## Changeset

-   [ ] I have verified if my change requires a changeset

## Related tasks and documents
(COM-1083)[https://vivid-planet.atlassian.net/browse/COM-1083]

## Open TODOs/questions
- [ ] refactor styling in `UserHeaderItem`

## Further information
Depends on #2490

2024-10-01 13:20 UTC, MattMountain requested changes

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> +            {groupTitle && (
Could work here with the Early return pattern, so you have no conditional rendering at the code and make the code better readable.

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> +                <Typography variant="overline" color={(theme) => theme.palette.grey[500]} sx={{ padding: "20px 15px 0 15px" }} {...typographyProps}>
You use a Mui Component, so you can also do the styling if you inheritance the component and don`t use inline styling.

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/cms-admin/src/common/header/UserHeaderItem.tsx
> +                sx={{
Here is the same issue like above, it would be nicer if you inheritance, the component from Mui

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/cms-admin/src/userPermissions/UserGrid.tsx
> +                        {isAllowed("impersonation") && (
Here would be better for the readability to use a own Component and use the early return pattern for the condition you use.

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/cms-admin/src/userPermissions/user/UserPage.tsx
> +                {userId !== currentUser.id && isAllowed("impersonation") && (
I would suggest you use there a own component and also use the Early Return pattern for your conditions.

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/cms-admin/src/userPermissions/user/UserPage.tsx
> +                            isAllowed("impersonation")
Here a example how you can improve your conditions and make your code more readabile

`const impersonateButton = ({ userId, currentUser, startImpersonation, isAllowed }) => {
    // Destructure currentUser.id for cleaner usage
    const { id: currentUserId } = currentUser;

    // If impersonation is not allowed, return null early
    if (!isAllowed("impersonation")) return null;

    // Create memoized onClick handler
    const handleImpersonation = useCallback(() => startImpersonation(userId), [userId, startImpersonation]);

    return {
        label: <FormattedMessage id="comet.impersonate" defaultMessage="Impersonate" />,
        icon: <ImpersonateUser />,
        disabled: userId === currentUserId, // Use destructured currentUserId
        onClick: handleImpersonation, // Use memoized handler
    };
};
`

2024-10-01 13:20 UTC, MattMountain commented on packages/admin/cms-admin/src/userPermissions/user/UserPage.tsx
> +                            currentUser.impersonated
The same like above.

2024-10-31 10:42 UTC, juliawegmayr commented
Closed.
UI for impersonation feature can be found here: https://github.com/vivid-planet/comet/pull/2698

2024-10-31 10:42 UTC, closed without merging