Fix hover styling of ToolbarBackButton
vivid-planet/comet pull request #2608
Opened 2024-10-07 16:25 UTC by fichtnerma

## Description
Fix Hover Styling of ToolbarBackButton so that the circle behind the IconButton is round

## Example

-   [ ] I have verified if my change requires an example

## Screenshots/screencasts
![image](https://github.com/user-attachments/assets/ff1032e7-357f-42c0-a753-f5bb0af9c162)

## Changeset

-   [ ] I have verified if my change requires a changeset

## Related tasks and documents
https://vivid-planet.atlassian.net/browse/COM-1110

2024-10-08 06:46 UTC, johnnyomair commented on packages/admin/admin/src/common/toolbar/backbutton/ToolbarBackButton.tsx
> +            }
Is this really the best solution? How about removing the [align-items: stretch](https://github.com/vivid-planet/comet/pull/2608/files#diff-b6f0a2a7b1a8191c6cd7a515c272d3c4f8e7bca71698abbe1c7c20838ac6a273R20) style instead? Also, we don't select via HTML elements in the Admin

2024-10-23 09:30 UTC, johnnyomair requested changes

2024-10-23 09:30 UTC, johnnyomair commented on packages/admin/admin/src/common/toolbar/backbutton/ToolbarBackButton.tsx
> +            }
Please remove this empty selector

2024-10-30 07:13 UTC, jamesricky approved these changes

2024-10-30 10:15 UTC, johnnyomair approved these changes

2024-10-30 10:15 UTC, merged