Remove old toolbar breadcrumbs
vivid-planet/comet pull request #2705
Opened 2024-11-05 09:53 UTC by juliawegmayr

## Description

## Example

-   [ ] I have verified if my change requires an example

## Screenshots/screencasts

## Changeset

-   [ ] I have verified if my change requires a changeset

## Related tasks and documents

## Open TODOs/questions

## Further information

2024-11-26 08:25 UTC, jamesricky requested changes
Please add a changeset for this breaking change. 
Even if the usage doesn't change in most use-cases, the props and class-keys have changed which could break existing usages or custom styling.

2024-11-26 12:48 UTC, juliawegmayr commented
> Please add a changeset for this breaking change. Even if the usage doesn't change in most use-cases, the props and class-keys have changed which could break existing usages or custom styling.

Thanks for pointing this out. I thought, that the usage would stay the same. Do I need to include more information on how to use the new ones...? d23646eea4ca4c4b013f6bcc98adf3847e4153b2

2024-11-26 14:13 UTC, jamesricky commented
> > Please add a changeset for this breaking change. Even if the usage doesn't change in most use-cases, the props and class-keys have changed which could break existing usages or custom styling.
> 
> Thanks for pointing this out. I thought, that the usage would stay the same. Do I need to include more information on how to use the new ones...? [d23646e](https://github.com/vivid-planet/comet/commit/d23646eea4ca4c4b013f6bcc98adf3847e4153b2)

I'm not actually too sure, what the difference is 😅 

If the usage and use-cases of the new component is very similar then it's probably enough to just mention that the props and class-keys have changed. 

If there is actually a change in how certain features of the component are used, you could add a before and after code example to the changeset.

2024-11-26 14:27 UTC, jamesricky commented on .changeset/rich-spiders-trade.md
> +Remove old `ToolbarBreadcrumbs`, `ToolbarBreadcrumbsClassKey` and `ToolbarBreadcrumbsProps`. Use new ones instead.
To the users of comet, nothing really is removed, they just see that `ToolbarBreadcrumbs` now looks differently and may have different props/class-keys. 

```suggestion
Redesign the `ToolbarBreadcrumbs` component

Due to internal changes, including the props and class keys, custom usages and styling may need to be adjusted. 
```

2024-11-27 11:36 UTC, jamesricky approved these changes

2024-11-28 13:27 UTC, johnnyomair approved these changes

2024-11-28 13:27 UTC, merged