COM-1263 Prevent import of mui tooltip
vivid-planet/comet pull request #2833
Opened 2024-11-26 19:22 UTC by juliawegmayr

## Description

Prevent imports of `Tooltip` from `@mui/material`

## Changeset

-   [x] I have verified if my change requires a changeset

## Related tasks and documents

(https://vivid-planet.atlassian.net/browse/COM-1263)

2024-11-28 12:18 UTC, johnnyomair reviewed
This could fixed automatically in our projects by creating an upgrade script. Are you up for a challenge?

2024-11-28 12:20 UTC, johnnyomair requested changes
Please add a section to the upgrade guide.

2024-12-12 08:05 UTC, juliawegmayr commented
> Please add a section to the upgrade guide.

Added here: 24cd93df921972878483c4c806de7686839d0d87

2024-12-16 08:28 UTC, juliawegmayr commented on docs/docs/migration/migration-from-v7-to-v8.md
> +````diff
4fae84c1439243cabe1c59022497963a5b71b834

2024-12-18 15:18 UTC, johnnyomair submitted a review, later dismissed

2024-12-18 15:19 UTC, johnnyomair commented
@juliawegmayr please resolve conflicts.

2024-12-19 13:18 UTC, johnnyomair approved these changes

2024-12-19 13:18 UTC, merged