Refactor menu styling
vivid-planet/comet pull request #2919
Opened 2024-12-11 13:40 UTC by juliawegmayr

## Description

Current State:

The CrudMoreActionsMenu contains quite a bit of custom styling. Ideally, this shouldn't be necessary.

Therefor move the custom styling from the component (applied via sx props) to the theme wherever it is possible and makes sense:

- Divider (only in Menus)
- MenuItem
- ListItemIcon

## Acceptance criteria

-   [x] I have verified if my change requires [an example](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md#example): 
-   [ ] I have verified if my change requires [a changeset](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md#changeset)
-   [ ] I have verified if my change requires [screenshots/screencasts](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md#screenshotsscreencasts)

## Screenshots/screencasts

| Before | After |
| ------ | ----- |
| Link   | Link  |

## Open TODOs/questions

-   [ ] Add changeset

## Further information

-   Task: https://vivid-planet.atlassian.net/browse/COM-1094

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiListItemIcon.tsx
> +    },
`defaultProps` are already included with `...component`

```suggestion
```

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +    },
`defaultProps` are already included with `...component`

```suggestion
```

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiListItemIcon.tsx
> +            minWidth: "unset !important",
Please override the `min-width` using a more precise selector to remove the `!important`. 
As you can see in the dev-tools, MUI sets the `min-width` from `MuiMenuItem` onto `MuiListItemIcon`, so you should be able to override this by setting the style on `.MuiListItemIcon-root` inside `getMuiMenuItem`. 

Also I'd slightly prefer the actual initial value of `minWidth` instead of using `unset` as this makes it a bit easier to see what style is actually set. 

<img width="259" alt="MinWidth in the Dev-Tools" src="https://github.com/user-attachments/assets/2871c102-95f0-41b3-859b-a0272c5ea353" />

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                padding: "8px 15px 8px 30px !important",
I don't think you need the `!important` here 🤔 

```suggestion
                padding: "8px 15px 8px 30px",
```

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                borderColor: theme.palette.grey[50],
Should the color of `Divider` really only be set to this value inside `Menu`, or should all instances have this color? 🤔

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> +export type CrudMoreActionsMenuClassKey = "root" | "group" | "button" | "chip";
Why remove these slots? 
This is a breaking change that removes the ability to override styles/props.

2025-01-02 07:53 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                margin: "8px 10px",
The `margin` is overridden by MUI here. Is it actually necessary?

<img width="346" alt="Dev-Tools" src="https://github.com/user-attachments/assets/7dfd38aa-3ae2-48c0-bfc2-6e2394857a68" />

2025-01-02 09:01 UTC, juliawegmayr commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                borderColor: theme.palette.grey[50],
As far as I can tell, the divider has the color grey[100] except in the Menu. At least I tried to find any other example in the design and couldn't find one 🤔

2025-01-02 09:05 UTC, juliawegmayr commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                margin: "8px 10px",
In the design, there is a margin: https://www.figma.com/design/Swzee5YSEkPVlCXHcyL7mp/COMET-DXP-Library?node-id=1228-15195&p=f&t=oWCjlOWwDfWYFGXW-0 - that's why I added the margin here. Is there a better way to achieve this?

<img width="206" alt="Screenshot 2025-01-02 at 10 01 47" src="https://github.com/user-attachments/assets/dec9f3c2-75c1-4f49-b22b-35a740a23fa9" />

2025-01-02 10:11 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenu.tsx
> +                margin: "8px 10px",
> In the design, there is a margin

👍🏼 

> Is there a better way to achieve this?

You need a higher css specificity to prevent MUI from overriding your margin, probably best to mimic the selector that MUI uses: `.MuiMenuItem-root+.MuiDivider-root`.

2025-01-02 11:34 UTC, jamesricky commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> +export type CrudMoreActionsMenuClassKey = "root" | "group" | "button" | "chip";
I mean the slots themselves (components created with `createComponentSlot`), not just the values in the class-key type

2025-01-15 18:43 UTC, jamesricky commented on packages/admin/admin-theme/src/componentsTheme/MuiMenuItem.tsx
> +            },
I think it would make sense to set this for every `ListItemIcon` (in `getListItemIcon.ts`), otherwise those inside `MenuItem` and `ListItem` could differ in styling.

2025-01-15 18:43 UTC, jamesricky commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> -        divider: dividerProps,
The `dividerProps` should probably still be used and applied to both instances of `<CrudMoreActionsDivider />`, just like before this refactor.

2025-01-20 07:42 UTC, johnnyomair commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> -    divider?: boolean;
Can we remove this prop? Isn't this part of the component's public API?

2025-01-20 08:31 UTC, jamesricky commented on packages/admin/admin/src/dataGrid/CrudMoreActionsMenu.tsx
> -    divider?: boolean;
It already exists from the extending `ComponentProps<typeof MenuItem>` so it does not need to be defined here as well.

2025-01-21 08:32 UTC, jamesricky submitted a review, later dismissed

2025-01-21 13:36 UTC, johnnyomair requested changes
Conflicts need to be resolved.

2025-01-21 14:37 UTC, johnnyomair approved these changes

2025-01-21 14:37 UTC, merged