Fix DAM DnD
vivid-planet/comet pull request #648
Opened 2022-06-28 09:18 UTC by thomasdax98

- update react-dnd
- update react-dropzone
- add mime-db to admin to conform to the [new react-dropzone accept format](https://react-dropzone.org/#!/Accepting%20specific%20file%20types)
- fix override of react-dnd's ref by react-dropzone

2022-06-28 09:23 UTC, johnnyomair requested changes

2022-06-28 10:30 UTC, thomasdax98 commented on packages/admin/cms-admin/src/dam/Table/fileUpload/useFileUpload.tsx
> +                if (!Object.keys(accept).includes(fileRejection.file.type)) {
I converted it to Map

2022-07-05 06:41 UTC, johnnyomair approved these changes

2022-07-05 06:41 UTC, johnnyomair commented
@thomasdax98 please fix the pipeline.

2022-07-05 09:15 UTC, merged