Remove ForkTsCheckerWebpackPlugin from webpack config
vivid-planet/comet pull request #749
Opened 2022-08-23 08:33 UTC by nsams

Doesn't log eslint/tsc errors in browser anymore, as I find that non helpful and spams the console only.
The IDE should be used for that.

And for cicd and production we have a dedicated lint pipeline (and this plugin was not used before)

(TODO: change that also in starter)

2022-08-23 08:37 UTC, dkarnutsch requested changes
The import and install can be removed as well

2022-08-23 11:05 UTC, dkarnutsch approved these changes

2022-08-29 07:35 UTC, johnnyomair commented
@nsams please resolve conflicts

2022-09-09 08:32 UTC, nsams commented
@johnnyomair done

2022-09-12 06:00 UTC, johnnyomair approved these changes

2022-09-12 06:32 UTC, merged