change name of menu item
vivid-planet/comet pull request #752
Opened 2022-08-24 18:37 UTC by F10Ragger

change name

2022-08-29 08:28 UTC, johnnyomair commented on packages/admin/cms-admin/src/pages/pageTree/PageContextMenu.tsx
> +                        <ListItemText primary={intl.formatMessage({ id: "comet.generic.editContent", defaultMessage: "Edit Content" })} />
```suggestion
                        <ListItemText primary={intl.formatMessage({ id: "comet.generic.editContent", defaultMessage: "Edit content" })} />
```

2022-08-29 08:34 UTC, johnnyomair commented
The commit message and title of this PR are rather generic. It would be better if you would describe why it has been changed, and not that it has been changed.

For example

Improve edit content menu item wording
Using only "Content" for the edit content menu item is confusing for our users. We therefore change it to "Edit content" for better understanding.

2022-08-30 08:12 UTC, johnnyomair commented on packages/admin/cms-admin/src/pages/pageTree/PageContextMenu.tsx
> +                        <ListItemText primary={intl.formatMessage({ id: "comet.generic.editContent", defaultMessage: "Edit content" })} />
```suggestion
                        <ListItemText primary={intl.formatMessage({ id: "comet.pages.pages.page.editContent", defaultMessage: "Edit content" })} />
```

This is not a generic message 😉

2022-08-30 08:13 UTC, johnnyomair approved these changes

2022-08-30 08:40 UTC, dkarnutsch requested changes

2022-08-30 08:40 UTC, dkarnutsch commented on packages/admin/cms-admin/src/pages/pageTree/PageContextMenu.tsx
> +                        <ListItemText primary={intl.formatMessage({ id: "comet.pages.pages.page.editContent", defaultMessage: "Edit content" })} />
```suggestion
                        <ListItemText primary={<FormattedMessage id="comet.pages.pages.page.editContent" defaultMessage="Edit content" />} />
```

Please stick with the FormattedMessage

2022-08-31 06:16 UTC, dkarnutsch approved these changes

2022-08-31 06:16 UTC, merged